const peliculas = [
  {
    "titulo": "Camino sin retorno 2",
    "año": 2007,
    "clasificacion": "NC-17",
    "duracion": "89 min",
    "genero": "Suspenso",
    "pais": "Francia",
    "idioma": "Francés",
    "director": "Director X.W.",
    "actores": "Actor 86, Actriz 145",
    "link": "https://www.netflix.com/watch/1576490"
  },
  {
    "titulo": "Ecos del silencio 5",
    "año": 2006,
    "clasificacion": "PG",
    "duracion": "81 min",
    "genero": "Drama",
    "pais": "EE.UU.",
    "idioma": "Español",
    "director": "Director G.T.",
    "actores": "Actor 2, Actriz 184",
    "link": "https://www.netflix.com/watch/2439466"
  },
  {
    "titulo": "Redención digital 4",
    "año": 2013,
    "clasificacion": "PG-13",
    "duracion": "140 min",
    "genero": "Romance",
    "pais": "EE.UU.",
    "idioma": "Coreano",
    "director": "Director M.F.",
    "actores": "Actor 14, Actriz 170",
    "link": "https://www.netflix.com/watch/2132916"
  },
  {
    "titulo": "La melodía del caos 2",
    "año": 2010,
    "clasificacion": "R",
    "duracion": "130 min",
    "genero": "Ciencia Ficción",
    "pais": "EE.UU.",
    "idioma": "Inglés",
    "director": "Director B.K.",
    "actores": "Actor 97, Actriz 124",
    "link": "https://www.netflix.com/watch/3271553"
  },
  {
    "titulo": "Camino sin retorno 2",
    "año": 2021,
    "clasificacion": "G",
    "duracion": "94 min",
    "genero": "Acción",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director Z.L.",
    "actores": "Actor 60, Actriz 124",
    "link": "https://www.netflix.com/watch/2946387"
  },
  {
    "titulo": "Camino sin retorno 5",
    "año": 2018,
    "clasificacion": "NC-17",
    "duracion": "103 min",
    "genero": "Suspenso",
    "pais": "España",
    "idioma": "Francés",
    "director": "Director M.A.",
    "actores": "Actor 41, Actriz 193",
    "link": "https://www.netflix.com/watch/1247693"
  },
  {
    "titulo": "El guardián del abismo 4",
    "año": 2000,
    "clasificacion": "PG-13",
    "duracion": "91 min",
    "genero": "Romance",
    "pais": "India",
    "idioma": "Coreano",
    "director": "Director E.J.",
    "actores": "Actor 99, Actriz 177",
    "link": "https://www.netflix.com/watch/3573358"
  },
  {
    "titulo": "La sombra del tiempo 1",
    "año": 2019,
    "clasificacion": "PG-13",
    "duracion": "88 min",
    "genero": "Comedia",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director N.L.",
    "actores": "Actor 64, Actriz 153",
    "link": "https://www.netflix.com/watch/1404081"
  },
  {
    "titulo": "Más allá del velo 3",
    "año": 2019,
    "clasificacion": "PG-13",
    "duracion": "113 min",
    "genero": "Acción",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director O.A.",
    "actores": "Actor 29, Actriz 198",
    "link": "https://www.netflix.com/watch/8891337"
  },
  {
    "titulo": "La melodía del caos 1",
    "año": 2016,
    "clasificacion": "G",
    "duracion": "133 min",
    "genero": "Suspenso",
    "pais": "EE.UU.",
    "idioma": "Español",
    "director": "Director N.J.",
    "actores": "Actor 85, Actriz 109",
    "link": "https://www.netflix.com/watch/1630991"
  },
  {
    "titulo": "Más allá del velo 1",
    "año": 2021,
    "clasificacion": "R",
    "duracion": "127 min",
    "genero": "Romance",
    "pais": "España",
    "idioma": "Hindi",
    "director": "Director A.H.",
    "actores": "Actor 15, Actriz 196",
    "link": "https://www.netflix.com/watch/4240286"
  },
  {
    "titulo": "Sueños de acero 1",
    "año": 1995,
    "clasificacion": "PG",
    "duracion": "108 min",
    "genero": "Drama",
    "pais": "Canadá",
    "idioma": "Español",
    "director": "Director F.B.",
    "actores": "Actor 8, Actriz 123",
    "link": "https://www.netflix.com/watch/6219557"
  },
  {
    "titulo": "Sueños de acero 2",
    "año": 2014,
    "clasificacion": "G",
    "duracion": "110 min",
    "genero": "Romance",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director R.J.",
    "actores": "Actor 13, Actriz 175",
    "link": "https://www.netflix.com/watch/7928290"
  },
  {
    "titulo": "Más allá del velo 1",
    "año": 2012,
    "clasificacion": "PG-13",
    "duracion": "87 min",
    "genero": "Romance",
    "pais": "Corea del Sur",
    "idioma": "Coreano",
    "director": "Director U.H.",
    "actores": "Actor 100, Actriz 146",
    "link": "https://www.netflix.com/watch/7790443"
  },
  {
    "titulo": "Más allá del velo 3",
    "año": 2020,
    "clasificacion": "R",
    "duracion": "125 min",
    "genero": "Romance",
    "pais": "Corea del Sur",
    "idioma": "Hindi",
    "director": "Director L.L.",
    "actores": "Actor 31, Actriz 132",
    "link": "https://www.netflix.com/watch/7236798"
  },
  {
    "titulo": "Código secreto 4",
    "año": 2020,
    "clasificacion": "PG-13",
    "duracion": "85 min",
    "genero": "Suspenso",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director S.R.",
    "actores": "Actor 59, Actriz 183",
    "link": "https://www.netflix.com/watch/9053728"
  },
  {
    "titulo": "Destino final 2",
    "año": 2022,
    "clasificacion": "PG",
    "duracion": "150 min",
    "genero": "Suspenso",
    "pais": "Canadá",
    "idioma": "Inglés",
    "director": "Director H.Z.",
    "actores": "Actor 81, Actriz 184",
    "link": "https://www.netflix.com/watch/8117636"
  },
  {
    "titulo": "Destino final 3",
    "año": 2018,
    "clasificacion": "G",
    "duracion": "150 min",
    "genero": "Suspenso",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director J.J.",
    "actores": "Actor 10, Actriz 102",
    "link": "https://www.netflix.com/watch/8509461"
  },
  {
    "titulo": "Sueños de acero 3",
    "año": 2002,
    "clasificacion": "PG-13",
    "duracion": "129 min",
    "genero": "Acción",
    "pais": "EE.UU.",
    "idioma": "Hindi",
    "director": "Director I.O.",
    "actores": "Actor 76, Actriz 185",
    "link": "https://www.netflix.com/watch/2446555"
  },
  {
    "titulo": "Crónicas del futuro 5",
    "año": 1996,
    "clasificacion": "R",
    "duracion": "139 min",
    "genero": "Acción",
    "pais": "España",
    "idioma": "Inglés",
    "director": "Director P.O.",
    "actores": "Actor 82, Actriz 171",
    "link": "https://www.netflix.com/watch/8683456"
  },
  {
    "titulo": "Camino sin retorno 5",
    "año": 2001,
    "clasificacion": "G",
    "duracion": "83 min",
    "genero": "Suspenso",
    "pais": "España",
    "idioma": "Coreano",
    "director": "Director P.T.",
    "actores": "Actor 80, Actriz 144",
    "link": "https://www.netflix.com/watch/4938849"
  },
  {
    "titulo": "Código secreto 1",
    "año": 1996,
    "clasificacion": "R",
    "duracion": "150 min",
    "genero": "Acción",
    "pais": "España",
    "idioma": "Español",
    "director": "Director J.O.",
    "actores": "Actor 4, Actriz 179",
    "link": "https://www.netflix.com/watch/5638651"
  },
  {
    "titulo": "En la mente del asesino 1",
    "año": 2001,
    "clasificacion": "R",
    "duracion": "102 min",
    "genero": "Suspenso",
    "pais": "EE.UU.",
    "idioma": "Hindi",
    "director": "Director R.W.",
    "actores": "Actor 75, Actriz 184",
    "link": "https://www.netflix.com/watch/4337300"
  },
  {
    "titulo": "Crónicas del futuro 1",
    "año": 2008,
    "clasificacion": "NC-17",
    "duracion": "126 min",
    "genero": "Drama",
    "pais": "México",
    "idioma": "Español",
    "director": "Director H.D.",
    "actores": "Actor 40, Actriz 106",
    "link": "https://www.netflix.com/watch/2618609"
  },
  {
    "titulo": "La melodía del caos 4",
    "año": 2023,
    "clasificacion": "R",
    "duracion": "97 min",
    "genero": "Acción",
    "pais": "EE.UU.",
    "idioma": "Coreano",
    "director": "Director D.R.",
    "actores": "Actor 63, Actriz 154",
    "link": "https://www.netflix.com/watch/2110583"
  },
  {
    "titulo": "Más allá del velo 2",
    "año": 2024,
    "clasificacion": "G",
    "duracion": "130 min",
    "genero": "Ciencia Ficción",
    "pais": "Corea del Sur",
    "idioma": "Español",
    "director": "Director Q.Z.",
    "actores": "Actor 95, Actriz 171",
    "link": "https://www.netflix.com/watch/9033108"
  },
  {
    "titulo": "En la mente del asesino 5",
    "año": 1999,
    "clasificacion": "NC-17",
    "duracion": "89 min",
    "genero": "Drama",
    "pais": "Corea del Sur",
    "idioma": "Español",
    "director": "Director A.L.",
    "actores": "Actor 63, Actriz 177",
    "link": "https://www.netflix.com/watch/5820979"
  },
  {
    "titulo": "Sueños de acero 2",
    "año": 2006,
    "clasificacion": "PG-13",
    "duracion": "136 min",
    "genero": "Comedia",
    "pais": "España",
    "idioma": "Coreano",
    "director": "Director B.U.",
    "actores": "Actor 100, Actriz 195",
    "link": "https://www.netflix.com/watch/2921176"
  },
  {
    "titulo": "La melodía del caos 4",
    "año": 2023,
    "clasificacion": "PG-13",
    "duracion": "115 min",
    "genero": "Drama",
    "pais": "España",
    "idioma": "Francés",
    "director": "Director A.H.",
    "actores": "Actor 19, Actriz 199",
    "link": "https://www.netflix.com/watch/9440238"
  },
  {
    "titulo": "Código secreto 1",
    "año": 2024,
    "clasificacion": "NC-17",
    "duracion": "123 min",
    "genero": "Romance",
    "pais": "México",
    "idioma": "Francés",
    "director": "Director P.S.",
    "actores": "Actor 86, Actriz 198",
    "link": "https://www.netflix.com/watch/6151405"
  },
  {
    "titulo": "Más allá del velo 3",
    "año": 2021,
    "clasificacion": "PG",
    "duracion": "119 min",
    "genero": "Romance",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director I.W.",
    "actores": "Actor 33, Actriz 121",
    "link": "https://www.netflix.com/watch/7867628"
  },
  {
    "titulo": "Más allá del velo 5",
    "año": 2023,
    "clasificacion": "NC-17",
    "duracion": "91 min",
    "genero": "Terror",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director H.X.",
    "actores": "Actor 46, Actriz 119",
    "link": "https://www.netflix.com/watch/7404971"
  },
  {
    "titulo": "El guardián del abismo 3",
    "año": 2003,
    "clasificacion": "NC-17",
    "duracion": "99 min",
    "genero": "Terror",
    "pais": "México",
    "idioma": "Coreano",
    "director": "Director D.Q.",
    "actores": "Actor 93, Actriz 188",
    "link": "https://www.netflix.com/watch/2962973"
  },
  {
    "titulo": "Crónicas del futuro 2",
    "año": 2017,
    "clasificacion": "PG-13",
    "duracion": "91 min",
    "genero": "Suspenso",
    "pais": "España",
    "idioma": "Hindi",
    "director": "Director T.B.",
    "actores": "Actor 61, Actriz 171",
    "link": "https://www.netflix.com/watch/7198445"
  },
  {
    "titulo": "Sueños de acero 3",
    "año": 2006,
    "clasificacion": "NC-17",
    "duracion": "91 min",
    "genero": "Comedia",
    "pais": "Corea del Sur",
    "idioma": "Francés",
    "director": "Director M.I.",
    "actores": "Actor 87, Actriz 169",
    "link": "https://www.netflix.com/watch/2507595"
  },
  {
    "titulo": "Camino sin retorno 4",
    "año": 2011,
    "clasificacion": "G",
    "duracion": "111 min",
    "genero": "Drama",
    "pais": "India",
    "idioma": "Inglés",
    "director": "Director N.Q.",
    "actores": "Actor 79, Actriz 130",
    "link": "https://www.netflix.com/watch/6445345"
  },
  {
    "titulo": "La sombra del tiempo 1",
    "año": 1998,
    "clasificacion": "NC-17",
    "duracion": "114 min",
    "genero": "Ciencia Ficción",
    "pais": "EE.UU.",
    "idioma": "Coreano",
    "director": "Director E.V.",
    "actores": "Actor 81, Actriz 139",
    "link": "https://www.netflix.com/watch/3250568"
  },
  {
    "titulo": "Código secreto 1",
    "año": 2013,
    "clasificacion": "PG-13",
    "duracion": "134 min",
    "genero": "Acción",
    "pais": "México",
    "idioma": "Francés",
    "director": "Director V.L.",
    "actores": "Actor 95, Actriz 158",
    "link": "https://www.netflix.com/watch/1176289"
  },
  {
    "titulo": "El guardián del abismo 1",
    "año": 2009,
    "clasificacion": "R",
    "duracion": "147 min",
    "genero": "Terror",
    "pais": "India",
    "idioma": "Inglés",
    "director": "Director F.L.",
    "actores": "Actor 96, Actriz 157",
    "link": "https://www.netflix.com/watch/3676075"
  },
  {
    "titulo": "Redención digital 5",
    "año": 2023,
    "clasificacion": "R",
    "duracion": "84 min",
    "genero": "Terror",
    "pais": "Corea del Sur",
    "idioma": "Inglés",
    "director": "Director X.Y.",
    "actores": "Actor 10, Actriz 149",
    "link": "https://www.netflix.com/watch/9740567"
  },
  {
    "titulo": "Ecos del silencio 1",
    "año": 2011,
    "clasificacion": "PG-13",
    "duracion": "120 min",
    "genero": "Terror",
    "pais": "Canadá",
    "idioma": "Francés",
    "director": "Director P.J.",
    "actores": "Actor 69, Actriz 118",
    "link": "https://www.netflix.com/watch/2117554"
  },
  {
    "titulo": "En la mente del asesino 4",
    "año": 2022,
    "clasificacion": "NC-17",
    "duracion": "133 min",
    "genero": "Drama",
    "pais": "India",
    "idioma": "Coreano",
    "director": "Director H.R.",
    "actores": "Actor 92, Actriz 136",
    "link": "https://www.netflix.com/watch/9758039"
  },
  {
    "titulo": "Redención digital 4",
    "año": 2019,
    "clasificacion": "G",
    "duracion": "94 min",
    "genero": "Romance",
    "pais": "Francia",
    "idioma": "Coreano",
    "director": "Director P.C.",
    "actores": "Actor 30, Actriz 185",
    "link": "https://www.netflix.com/watch/7343737"
  },
  {
    "titulo": "Más allá del velo 2",
    "año": 2021,
    "clasificacion": "NC-17",
    "duracion": "129 min",
    "genero": "Romance",
    "pais": "EE.UU.",
    "idioma": "Francés",
    "director": "Director R.I.",
    "actores": "Actor 16, Actriz 196",
    "link": "https://www.netflix.com/watch/1527108"
  },
  {
    "titulo": "Destino final 3",
    "año": 2011,
    "clasificacion": "G",
    "duracion": "140 min",
    "genero": "Suspenso",
    "pais": "España",
    "idioma": "Hindi",
    "director": "Director I.Z.",
    "actores": "Actor 70, Actriz 122",
    "link": "https://www.netflix.com/watch/6118497"
  },
  {
    "titulo": "La sombra del tiempo 5",
    "año": 2003,
    "clasificacion": "PG-13",
    "duracion": "100 min",
    "genero": "Romance",
    "pais": "Canadá",
    "idioma": "Inglés",
    "director": "Director H.O.",
    "actores": "Actor 88, Actriz 181",
    "link": "https://www.netflix.com/watch/9924978"
  },
  {
    "titulo": "Redención digital 4",
    "año": 2020,
    "clasificacion": "NC-17",
    "duracion": "97 min",
    "genero": "Romance",
    "pais": "Corea del Sur",
    "idioma": "Coreano",
    "director": "Director V.T.",
    "actores": "Actor 9, Actriz 157",
    "link": "https://www.netflix.com/watch/1784722"
  },
  {
    "titulo": "Destino final 4",
    "año": 2017,
    "clasificacion": "R",
    "duracion": "100 min",
    "genero": "Terror",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director A.V.",
    "actores": "Actor 91, Actriz 133",
    "link": "https://www.netflix.com/watch/8450816"
  },
  {
    "titulo": "La melodía del caos 1",
    "año": 2003,
    "clasificacion": "NC-17",
    "duracion": "110 min",
    "genero": "Suspenso",
    "pais": "España",
    "idioma": "Inglés",
    "director": "Director F.T.",
    "actores": "Actor 10, Actriz 161",
    "link": "https://www.netflix.com/watch/2816427"
  },
  {
    "titulo": "Redención digital 1",
    "año": 2005,
    "clasificacion": "G",
    "duracion": "139 min",
    "genero": "Comedia",
    "pais": "Canadá",
    "idioma": "Francés",
    "director": "Director N.A.",
    "actores": "Actor 39, Actriz 162",
    "link": "https://www.netflix.com/watch/7649166"
  },
  {
    "titulo": "Más allá del velo 1",
    "año": 1996,
    "clasificacion": "R",
    "duracion": "117 min",
    "genero": "Terror",
    "pais": "India",
    "idioma": "Coreano",
    "director": "Director M.S.",
    "actores": "Actor 24, Actriz 196",
    "link": "https://www.netflix.com/watch/3451523"
  },
  {
    "titulo": "En la mente del asesino 1",
    "año": 2014,
    "clasificacion": "PG-13",
    "duracion": "88 min",
    "genero": "Comedia",
    "pais": "EE.UU.",
    "idioma": "Francés",
    "director": "Director A.T.",
    "actores": "Actor 70, Actriz 134",
    "link": "https://www.netflix.com/watch/6426786"
  },
  {
    "titulo": "Destino final 5",
    "año": 2012,
    "clasificacion": "R",
    "duracion": "142 min",
    "genero": "Terror",
    "pais": "Francia",
    "idioma": "Francés",
    "director": "Director S.V.",
    "actores": "Actor 19, Actriz 141",
    "link": "https://www.netflix.com/watch/7033850"
  },
  {
    "titulo": "Sueños de acero 3",
    "año": 1999,
    "clasificacion": "R",
    "duracion": "101 min",
    "genero": "Comedia",
    "pais": "Canadá",
    "idioma": "Hindi",
    "director": "Director Y.C.",
    "actores": "Actor 25, Actriz 160",
    "link": "https://www.netflix.com/watch/7909661"
  },
  {
    "titulo": "En la mente del asesino 2",
    "año": 1999,
    "clasificacion": "G",
    "duracion": "127 min",
    "genero": "Suspenso",
    "pais": "Corea del Sur",
    "idioma": "Español",
    "director": "Director M.T.",
    "actores": "Actor 92, Actriz 153",
    "link": "https://www.netflix.com/watch/3974475"
  },
  {
    "titulo": "Código secreto 2",
    "año": 2020,
    "clasificacion": "PG",
    "duracion": "103 min",
    "genero": "Drama",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director J.F.",
    "actores": "Actor 7, Actriz 161",
    "link": "https://www.netflix.com/watch/6853641"
  },
  {
    "titulo": "Sueños de acero 4",
    "año": 1995,
    "clasificacion": "G",
    "duracion": "143 min",
    "genero": "Suspenso",
    "pais": "India",
    "idioma": "Coreano",
    "director": "Director I.P.",
    "actores": "Actor 51, Actriz 191",
    "link": "https://www.netflix.com/watch/7057674"
  },
  {
    "titulo": "El guardián del abismo 2",
    "año": 2016,
    "clasificacion": "NC-17",
    "duracion": "122 min",
    "genero": "Ciencia Ficción",
    "pais": "Canadá",
    "idioma": "Francés",
    "director": "Director J.U.",
    "actores": "Actor 55, Actriz 103",
    "link": "https://www.netflix.com/watch/4082266"
  },
  {
    "titulo": "La melodía del caos 4",
    "año": 2010,
    "clasificacion": "R",
    "duracion": "85 min",
    "genero": "Acción",
    "pais": "México",
    "idioma": "Español",
    "director": "Director I.Q.",
    "actores": "Actor 5, Actriz 137",
    "link": "https://www.netflix.com/watch/5690199"
  },
  {
    "titulo": "Camino sin retorno 3",
    "año": 2009,
    "clasificacion": "PG-13",
    "duracion": "120 min",
    "genero": "Suspenso",
    "pais": "México",
    "idioma": "Coreano",
    "director": "Director M.Z.",
    "actores": "Actor 42, Actriz 185",
    "link": "https://www.netflix.com/watch/1554427"
  },
  {
    "titulo": "Redención digital 1",
    "año": 2020,
    "clasificacion": "PG",
    "duracion": "113 min",
    "genero": "Ciencia Ficción",
    "pais": "Canadá",
    "idioma": "Inglés",
    "director": "Director Y.Q.",
    "actores": "Actor 21, Actriz 110",
    "link": "https://www.netflix.com/watch/9525748"
  },
  {
    "titulo": "El guardián del abismo 4",
    "año": 2019,
    "clasificacion": "PG-13",
    "duracion": "93 min",
    "genero": "Comedia",
    "pais": "Corea del Sur",
    "idioma": "Inglés",
    "director": "Director K.A.",
    "actores": "Actor 14, Actriz 147",
    "link": "https://www.netflix.com/watch/2776832"
  },
  {
    "titulo": "Crónicas del futuro 3",
    "año": 2023,
    "clasificacion": "PG-13",
    "duracion": "107 min",
    "genero": "Comedia",
    "pais": "Corea del Sur",
    "idioma": "Francés",
    "director": "Director V.F.",
    "actores": "Actor 65, Actriz 169",
    "link": "https://www.netflix.com/watch/9975925"
  },
  {
    "titulo": "Más allá del velo 5",
    "año": 2022,
    "clasificacion": "R",
    "duracion": "137 min",
    "genero": "Comedia",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director J.W.",
    "actores": "Actor 64, Actriz 148",
    "link": "https://www.netflix.com/watch/5840159"
  },
  {
    "titulo": "Ecos del silencio 2",
    "año": 2007,
    "clasificacion": "PG",
    "duracion": "138 min",
    "genero": "Drama",
    "pais": "Francia",
    "idioma": "Coreano",
    "director": "Director C.E.",
    "actores": "Actor 19, Actriz 196",
    "link": "https://www.netflix.com/watch/4791300"
  },
  {
    "titulo": "Ecos del silencio 2",
    "año": 1996,
    "clasificacion": "NC-17",
    "duracion": "114 min",
    "genero": "Romance",
    "pais": "Corea del Sur",
    "idioma": "Inglés",
    "director": "Director O.B.",
    "actores": "Actor 95, Actriz 164",
    "link": "https://www.netflix.com/watch/9988938"
  },
  {
    "titulo": "Más allá del velo 5",
    "año": 2002,
    "clasificacion": "R",
    "duracion": "94 min",
    "genero": "Terror",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director S.P.",
    "actores": "Actor 40, Actriz 115",
    "link": "https://www.netflix.com/watch/8209366"
  },
  {
    "titulo": "Más allá del velo 3",
    "año": 2014,
    "clasificacion": "PG-13",
    "duracion": "118 min",
    "genero": "Terror",
    "pais": "EE.UU.",
    "idioma": "Hindi",
    "director": "Director M.Z.",
    "actores": "Actor 91, Actriz 139",
    "link": "https://www.netflix.com/watch/2435320"
  },
  {
    "titulo": "Camino sin retorno 3",
    "año": 2000,
    "clasificacion": "NC-17",
    "duracion": "81 min",
    "genero": "Comedia",
    "pais": "Corea del Sur",
    "idioma": "Hindi",
    "director": "Director E.O.",
    "actores": "Actor 32, Actriz 172",
    "link": "https://www.netflix.com/watch/6912742"
  },
  {
    "titulo": "Código secreto 5",
    "año": 2024,
    "clasificacion": "PG-13",
    "duracion": "107 min",
    "genero": "Terror",
    "pais": "India",
    "idioma": "Coreano",
    "director": "Director U.T.",
    "actores": "Actor 60, Actriz 179",
    "link": "https://www.netflix.com/watch/1330376"
  },
  {
    "titulo": "Crónicas del futuro 3",
    "año": 1998,
    "clasificacion": "R",
    "duracion": "126 min",
    "genero": "Terror",
    "pais": "Canadá",
    "idioma": "Español",
    "director": "Director W.T.",
    "actores": "Actor 64, Actriz 143",
    "link": "https://www.netflix.com/watch/1892543"
  },
  {
    "titulo": "Crónicas del futuro 1",
    "año": 2009,
    "clasificacion": "G",
    "duracion": "102 min",
    "genero": "Suspenso",
    "pais": "Corea del Sur",
    "idioma": "Francés",
    "director": "Director A.A.",
    "actores": "Actor 23, Actriz 128",
    "link": "https://www.netflix.com/watch/1260084"
  },
  {
    "titulo": "Sueños de acero 4",
    "año": 2003,
    "clasificacion": "G",
    "duracion": "109 min",
    "genero": "Romance",
    "pais": "México",
    "idioma": "Español",
    "director": "Director J.F.",
    "actores": "Actor 4, Actriz 161",
    "link": "https://www.netflix.com/watch/9909693"
  },
  {
    "titulo": "Destino final 2",
    "año": 2000,
    "clasificacion": "PG",
    "duracion": "111 min",
    "genero": "Drama",
    "pais": "Corea del Sur",
    "idioma": "Coreano",
    "director": "Director G.S.",
    "actores": "Actor 69, Actriz 136",
    "link": "https://www.netflix.com/watch/1025320"
  },
  {
    "titulo": "Redención digital 2",
    "año": 2018,
    "clasificacion": "PG-13",
    "duracion": "89 min",
    "genero": "Ciencia Ficción",
    "pais": "Canadá",
    "idioma": "Francés",
    "director": "Director K.J.",
    "actores": "Actor 97, Actriz 138",
    "link": "https://www.netflix.com/watch/5013320"
  },
  {
    "titulo": "Sueños de acero 2",
    "año": 2005,
    "clasificacion": "PG-13",
    "duracion": "115 min",
    "genero": "Acción",
    "pais": "México",
    "idioma": "Español",
    "director": "Director I.E.",
    "actores": "Actor 59, Actriz 178",
    "link": "https://www.netflix.com/watch/4718007"
  },
  {
    "titulo": "En la mente del asesino 3",
    "año": 2013,
    "clasificacion": "G",
    "duracion": "148 min",
    "genero": "Acción",
    "pais": "India",
    "idioma": "Hindi",
    "director": "Director T.T.",
    "actores": "Actor 41, Actriz 113",
    "link": "https://www.netflix.com/watch/4636074"
  },
  {
    "titulo": "La sombra del tiempo 3",
    "año": 2011,
    "clasificacion": "PG-13",
    "duracion": "104 min",
    "genero": "Acción",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director U.M.",
    "actores": "Actor 22, Actriz 119",
    "link": "https://www.netflix.com/watch/7070140"
  },
  {
    "titulo": "Ecos del silencio 3",
    "año": 2000,
    "clasificacion": "R",
    "duracion": "147 min",
    "genero": "Suspenso",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director J.K.",
    "actores": "Actor 36, Actriz 127",
    "link": "https://www.netflix.com/watch/5490116"
  },
  {
    "titulo": "La melodía del caos 1",
    "año": 1995,
    "clasificacion": "PG-13",
    "duracion": "139 min",
    "genero": "Romance",
    "pais": "Corea del Sur",
    "idioma": "Francés",
    "director": "Director A.O.",
    "actores": "Actor 16, Actriz 116",
    "link": "https://www.netflix.com/watch/7121676"
  },
  {
    "titulo": "Destino final 5",
    "año": 2023,
    "clasificacion": "NC-17",
    "duracion": "133 min",
    "genero": "Drama",
    "pais": "EE.UU.",
    "idioma": "Inglés",
    "director": "Director J.M.",
    "actores": "Actor 1, Actriz 113",
    "link": "https://www.netflix.com/watch/4719471"
  },
  {
    "titulo": "Código secreto 5",
    "año": 2023,
    "clasificacion": "NC-17",
    "duracion": "102 min",
    "genero": "Suspenso",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director T.I.",
    "actores": "Actor 46, Actriz 169",
    "link": "https://www.netflix.com/watch/7977029"
  },
  {
    "titulo": "Camino sin retorno 4",
    "año": 2024,
    "clasificacion": "PG-13",
    "duracion": "126 min",
    "genero": "Suspenso",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director Q.N.",
    "actores": "Actor 50, Actriz 183",
    "link": "https://www.netflix.com/watch/2651805"
  },
  {
    "titulo": "Más allá del velo 5",
    "año": 2003,
    "clasificacion": "PG-13",
    "duracion": "128 min",
    "genero": "Comedia",
    "pais": "India",
    "idioma": "Francés",
    "director": "Director U.Z.",
    "actores": "Actor 76, Actriz 189",
    "link": "https://www.netflix.com/watch/4567001"
  },
  {
    "titulo": "Código secreto 5",
    "año": 1997,
    "clasificacion": "PG-13",
    "duracion": "124 min",
    "genero": "Romance",
    "pais": "EE.UU.",
    "idioma": "Coreano",
    "director": "Director L.M.",
    "actores": "Actor 93, Actriz 181",
    "link": "https://www.netflix.com/watch/5394145"
  },
  {
    "titulo": "La melodía del caos 5",
    "año": 2023,
    "clasificacion": "G",
    "duracion": "144 min",
    "genero": "Drama",
    "pais": "EE.UU.",
    "idioma": "Francés",
    "director": "Director G.O.",
    "actores": "Actor 67, Actriz 159",
    "link": "https://www.netflix.com/watch/3460018"
  },
  {
    "titulo": "Camino sin retorno 1",
    "año": 2015,
    "clasificacion": "G",
    "duracion": "135 min",
    "genero": "Terror",
    "pais": "México",
    "idioma": "Francés",
    "director": "Director W.E.",
    "actores": "Actor 69, Actriz 139",
    "link": "https://www.netflix.com/watch/8348350"
  },
  {
    "titulo": "Código secreto 1",
    "año": 2006,
    "clasificacion": "G",
    "duracion": "121 min",
    "genero": "Acción",
    "pais": "India",
    "idioma": "Hindi",
    "director": "Director A.P.",
    "actores": "Actor 89, Actriz 127",
    "link": "https://www.netflix.com/watch/2604833"
  },
  {
    "titulo": "En la mente del asesino 3",
    "año": 2001,
    "clasificacion": "G",
    "duracion": "137 min",
    "genero": "Ciencia Ficción",
    "pais": "España",
    "idioma": "Francés",
    "director": "Director V.U.",
    "actores": "Actor 74, Actriz 164",
    "link": "https://www.netflix.com/watch/8929274"
  },
  {
    "titulo": "Más allá del velo 2",
    "año": 2007,
    "clasificacion": "NC-17",
    "duracion": "107 min",
    "genero": "Terror",
    "pais": "Francia",
    "idioma": "Español",
    "director": "Director D.G.",
    "actores": "Actor 61, Actriz 161",
    "link": "https://www.netflix.com/watch/1437028"
  },
  {
    "titulo": "Sueños de acero 3",
    "año": 2011,
    "clasificacion": "R",
    "duracion": "113 min",
    "genero": "Ciencia Ficción",
    "pais": "México",
    "idioma": "Español",
    "director": "Director E.W.",
    "actores": "Actor 71, Actriz 131",
    "link": "https://www.netflix.com/watch/3034969"
  },
  {
    "titulo": "Más allá del velo 2",
    "año": 2002,
    "clasificacion": "PG",
    "duracion": "143 min",
    "genero": "Suspenso",
    "pais": "Canadá",
    "idioma": "Francés",
    "director": "Director F.F.",
    "actores": "Actor 78, Actriz 138",
    "link": "https://www.netflix.com/watch/1650359"
  },
  {
    "titulo": "Más allá del velo 5",
    "año": 2003,
    "clasificacion": "NC-17",
    "duracion": "134 min",
    "genero": "Romance",
    "pais": "Francia",
    "idioma": "Inglés",
    "director": "Director E.S.",
    "actores": "Actor 100, Actriz 132",
    "link": "https://www.netflix.com/watch/3974282"
  },
  {
    "titulo": "El guardián del abismo 5",
    "año": 2004,
    "clasificacion": "G",
    "duracion": "96 min",
    "genero": "Acción",
    "pais": "EE.UU.",
    "idioma": "Hindi",
    "director": "Director B.S.",
    "actores": "Actor 69, Actriz 161",
    "link": "https://www.netflix.com/watch/8907550"
  },
  {
    "titulo": "El guardián del abismo 1",
    "año": 1999,
    "clasificacion": "PG",
    "duracion": "109 min",
    "genero": "Drama",
    "pais": "India",
    "idioma": "Hindi",
    "director": "Director V.P.",
    "actores": "Actor 10, Actriz 118",
    "link": "https://www.netflix.com/watch/7740278"
  },
  {
    "titulo": "Crónicas del futuro 2",
    "año": 2022,
    "clasificacion": "PG-13",
    "duracion": "107 min",
    "genero": "Acción",
    "pais": "México",
    "idioma": "Coreano",
    "director": "Director G.Q.",
    "actores": "Actor 3, Actriz 149",
    "link": "https://www.netflix.com/watch/5015416"
  },
  {
    "titulo": "Código secreto 1",
    "año": 2023,
    "clasificacion": "NC-17",
    "duracion": "129 min",
    "genero": "Ciencia Ficción",
    "pais": "Francia",
    "idioma": "Francés",
    "director": "Director O.C.",
    "actores": "Actor 18, Actriz 126",
    "link": "https://www.netflix.com/watch/4241496"
  },
  {
    "titulo": "Más allá del velo 4",
    "año": 1998,
    "clasificacion": "NC-17",
    "duracion": "114 min",
    "genero": "Acción",
    "pais": "India",
    "idioma": "Español",
    "director": "Director M.A.",
    "actores": "Actor 66, Actriz 147",
    "link": "https://www.netflix.com/watch/8613060"
  },
  {
    "titulo": "Crónicas del futuro 5",
    "año": 2001,
    "clasificacion": "NC-17",
    "duracion": "114 min",
    "genero": "Ciencia Ficción",
    "pais": "India",
    "idioma": "Español",
    "director": "Director B.Z.",
    "actores": "Actor 39, Actriz 148",
    "link": "https://www.netflix.com/watch/7018778"
  },
  {
    "titulo": "Destino final 4",
    "año": 2011,
    "clasificacion": "G",
    "duracion": "132 min",
    "genero": "Comedia",
    "pais": "Canadá",
    "idioma": "Coreano",
    "director": "Director J.C.",
    "actores": "Actor 23, Actriz 154",
    "link": "https://www.netflix.com/watch/4021003"
  }
];